# Generated by Django 4.2.7 on 2023-11-17 16:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0002_funcionario_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipamento', models.CharField(max_length=200)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('cor', models.CharField(max_length=50)),
                ('nun_serie', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacao', models.TextField()),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.equipamento')),
            ],
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='Cliente',
            new_name='cliente',
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_entrada', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_saida', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('EN', 'Entrada'), ('OR', 'Orçamento'), ('MA', 'manutenção'), ('GA', 'entrega'), ('SA', 'Saida')], default='EN', max_length=2)),
                ('historico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.historico')),
            ],
        ),
        migrations.AddField(
            model_name='equipamento',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.cliente'),
        ),
    ]
