# Generated by Django 4.2.7 on 2023-11-17 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0003_equipamento_historico_rename_cliente_cliente_cliente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(choices=[('RC', 'Recepcionista'), ('TC', 'Técnico'), ('GE', 'Gerente')], default='EN', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setor', models.CharField(choices=[('RE', 'Recepção'), ('OF', 'Oficina'), ('ES', 'Estoque')], default='EN', max_length=2)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.status')),
            ],
        ),
        migrations.CreateModel(
            name='Cargo_funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.cargo')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.funcionario')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.setor')),
            ],
        ),
    ]
