# Generated by Django 4.2.7 on 2023-11-17 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0004_cargo_setor_cargo_funcionario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('preco', models.IntegerField(max_length=50)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('valor', models.IntegerField(max_length=50)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacao', models.TextField()),
                ('Cargo_funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.cargo_funcionario')),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.equipamento')),
                ('produto', models.ManyToManyField(to='workflow.produto')),
                ('servico', models.ManyToManyField(to='workflow.servico')),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cnpj', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=50)),
                ('descricao', models.TextField()),
                ('produtos', models.ManyToManyField(to='workflow.produto')),
            ],
        ),
    ]
